- type: job
  id: PartCommander
  name: job-name-part-commander
  description: job-description-combat
  playTimeTracker: JobPartCommander
  requirements:
  - !type:DepartmentTimeRequirement
    department: Combat
    time: 36000 #10 hrs
  startingGear: PartCommanderGear
  icon: "JobIconPartCommander"
  supervisors: job-supervisors-platoon
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Command
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: PartCommanderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    shoes: ClothingShoesBootsCombat
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    neck: ClothingNeckIDMarksPartCommander
