- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Deterrent
#  - Aspid
#  - Atlas
#  - Bagel
#  - Box
#  - Cluster
#  - Core
#  - Fland
#  - Gemini
#  - Marathon
#  - Meta
#  - Omega
#  - Origin
#  - Saltern
#  - Packed
#  - Reach
