# Department
- type: department
  id: Combat
  description: department-combat-description
  color: "#C3C3BD"
  roles:
  - JobMarine
  - JobMarineMedic
  - JobMarineEngineer
  - JobMarinePilot
  - JobPartCommander
  - JobPlatoonCommander


# Jobs
- type: playTimeTracker
  id: JobMarine

- type: playTimeTracker
  id: JobMarineMedic

- type: playTimeTracker
  id: JobMarineEngineer

- type: playTimeTracker
  id: JobPartCommander

- type: playTimeTracker
  id: JobPlatoonCommander

- type: playTimeTracker
  id: JobMarinePilot


# Job Icons
- type: statusIcon
  parent: JobIcon
  id: JobIconMarine
  icon:
    sprite: TS/Interface/job_icons.rsi
    state: Marine

- type: statusIcon
  parent: JobIcon
  id: JobIconJobMarineMedic
  icon:
    sprite: TS/Interface/job_icons.rsi
    state: JobMarineMedic

- type: statusIcon
  parent: JobIcon
  id: JobIconMarineEngineer
  icon:
    sprite: TS/Interface/job_icons.rsi
    state: MarineEngineer

- type: statusIcon
  parent: JobIcon
  id: JobIconMarinePilot
  icon:
    sprite: TS/Interface/job_icons.rsi
    state: MarinePilot

- type: statusIcon
  parent: JobIcon
  id: JobIconPartCommander
  icon:
    sprite: TS/Interface/job_icons.rsi
    state: PartCommander

- type: statusIcon
  parent: JobIcon
  id: JobIconPlatoonCommander
  icon:
    sprite: TS/Interface/job_icons.rsi
    state: PlatoonCommander
